# Generated by Django 5.1.1 on 2024-09-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_student_big_int_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='binary',
            field=models.BinaryField(default=b'\x00\x00\x00\x00'),
        ),
    ]
