# Generated by Django 5.1.1 on 2024-09-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_student_binary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='big_int_val',
        ),
        migrations.RemoveField(
            model_name='student',
            name='binary',
        ),
        migrations.AddField(
            model_name='student',
            name='boolean_field',
            field=models.BooleanField(default=True),
        ),
    ]
