# Generated by Django 5.1.1 on 2024-09-28 07:49

import datetime
import first_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_remove_student_big_int_val_remove_student_binary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='big_int_val',
            field=models.BigIntegerField(default=121323),
        ),
        migrations.AddField(
            model_name='student',
            name='binary',
            field=models.BinaryField(default=b'\x00\x00\x00\x00'),
        ),
        migrations.AddField(
            model_name='student',
            name='comma_separated_field',
            field=models.CharField(default='Rakib,Korim', max_length=255, validators=[first_app.models.comma_separated_validator]),
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
