# Generated by Django 5.1.1 on 2024-09-28 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_student_big_int_val_student_binary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='decimal',
            field=models.DecimalField(decimal_places=2, default=22.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='student',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1, seconds=19800)),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='rh44007@gmail.com', max_length=254),
        ),
    ]
