# Generated by Django 5.1.1 on 2024-09-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_student_decimal_student_duration_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='IpAddress',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='student',
            name='float',
            field=models.FloatField(default=1.22),
        ),
    ]
